version: '3.8'

services:
  db:
    image: postgres:15
    container_name: aln_postgres
    environment:
      POSTGRES_USER: aln_user
      POSTGRES_PASSWORD: aln_password
      POSTGRES_DB: aln_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
