"""skill_embeddings

Revision ID: 2973a14662f1
Revises: 40407856ffc8
Create Date: 2026-08-27 09:09:48.297417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2973a14662f1'
down_revision: Union[str, Sequence[str], None] = '40407856ffc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('aliases', sa.Text(), nullable=True))
    op.add_column('skills', sa.Column('parent_skill_id', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('embedding', sa.Text(), nullable=True))
    op.add_column('skills', sa.Column('embedding_model', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('embedding_version', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('embedding_content_hash', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('skills', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'skills', 'skills', ['parent_skill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'created_at')
    op.drop_column('skills', 'embedding_updated_at')
    op.drop_column('skills', 'embedding_content_hash')
    op.drop_column('skills', 'embedding_version')
    op.drop_column('skills', 'embedding_model')
    op.drop_column('skills', 'embedding')
    op.drop_column('skills', 'parent_skill_id')
    op.drop_column('skills', 'aliases')
    # ### end Alembic commands ###
