"""ingestion_pipeline

Revision ID: 40407856ffc8
Revises: 
Create Date: 2026-08-26 21:16:47.375729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40407856ffc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('inserted_rows', sa.Integer(), nullable=True),
    sa.Column('updated_rows', sa.Integer(), nullable=True),
    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
    sa.Column('invalid_rows', sa.Integer(), nullable=True),
    sa.Column('validation_failed_rows', sa.Integer(), nullable=True),
    sa.Column('unknown_url_rows', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_job_id'), 'ingestion_jobs', ['job_id'], unique=True)
    op.add_column('resource_skills', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('resource_skills', sa.Column('mapping_source', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('canonical_url', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('resources', sa.Column('final_url', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('language', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('price_amount', sa.Float(), nullable=True))
    op.add_column('resources', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('resources', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('resources', sa.Column('popularity_score', sa.Float(), nullable=True))
    op.add_column('resources', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.execute("CREATE TYPE verificationstatus AS ENUM ('VERIFIED', 'STALE', 'FAILED', 'UNKNOWN')")
    op.add_column('resources', sa.Column('verification_status', sa.Enum('VERIFIED', 'STALE', 'FAILED', 'UNKNOWN', name='verificationstatus'), nullable=True))
    op.add_column('resources', sa.Column('http_status', sa.Integer(), nullable=True))
    op.add_column('resources', sa.Column('validation_error', sa.Text(), nullable=True))
    op.add_column('resources', sa.Column('dataset_name', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('dataset_version', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('ingestion_job_id', sa.Integer(), nullable=True))
    op.add_column('resources', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('resources', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('resources_url_key'), 'resources', type_='unique')
    op.create_index(op.f('ix_resources_canonical_url'), 'resources', ['canonical_url'], unique=True)
    op.create_foreign_key(None, 'resources', 'ingestion_jobs', ['ingestion_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_index(op.f('ix_resources_canonical_url'), table_name='resources')
    op.create_unique_constraint(op.f('resources_url_key'), 'resources', ['url'])
    op.drop_column('resources', 'updated_at')
    op.drop_column('resources', 'created_at')
    op.drop_column('resources', 'ingestion_job_id')
    op.drop_column('resources', 'dataset_version')
    op.drop_column('resources', 'dataset_name')
    op.drop_column('resources', 'validation_error')
    op.drop_column('resources', 'http_status')
    op.drop_column('resources', 'verification_status')
    op.drop_column('resources', 'metadata_json')
    op.drop_column('resources', 'thumbnail_url')
    op.drop_column('resources', 'popularity_score')
    op.drop_column('resources', 'review_count')
    op.drop_column('resources', 'rating')
    op.drop_column('resources', 'currency')
    op.drop_column('resources', 'price_amount')
    op.drop_column('resources', 'language')
    op.drop_column('resources', 'final_url')
    op.drop_column('resources', 'description')
    op.drop_column('resources', 'canonical_url')
    op.drop_column('resources', 'provider')
    op.drop_column('resources', 'external_id')
    op.drop_column('resource_skills', 'mapping_source')
    op.drop_column('resource_skills', 'confidence')
    op.drop_index(op.f('ix_ingestion_jobs_job_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.execute("DROP TYPE verificationstatus")
    # ### end Alembic commands ###
