"""ingestion_job_metrics

Revision ID: 6b5532f54b6f
Revises: 2973a14662f1
Create Date: 2026-08-27 09:11:19.413807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5532f54b6f'
down_revision: Union[str, Sequence[str], None] = '2973a14662f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('exact_matches', sa.Integer(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('alias_matches', sa.Integer(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('semantic_matches', sa.Integer(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('groq_reviewed', sa.Integer(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('unmapped_resources', sa.Integer(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('total_mappings', sa.Integer(), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('total_confidence_sum', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'total_confidence_sum')
    op.drop_column('ingestion_jobs', 'total_mappings')
    op.drop_column('ingestion_jobs', 'unmapped_resources')
    op.drop_column('ingestion_jobs', 'groq_reviewed')
    op.drop_column('ingestion_jobs', 'semantic_matches')
    op.drop_column('ingestion_jobs', 'alias_matches')
    op.drop_column('ingestion_jobs', 'exact_matches')
    # ### end Alembic commands ###
