"""Add ExplanationCache, PathTransition, UserSkillStreak

Revision ID: 9f8b1406c7a7
Revises: 6b5532f54b6f
Create Date: 2026-08-28 11:34:05.683155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8b1406c7a7'
down_revision: Union[str, Sequence[str], None] = '6b5532f54b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explanation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('target_goal', sa.String(), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanation_cache_id'), 'explanation_cache', ['id'], unique=False)
    op.create_index(op.f('ix_explanation_cache_skill_id'), 'explanation_cache', ['skill_id'], unique=False)
    op.create_index(op.f('ix_explanation_cache_target_goal'), 'explanation_cache', ['target_goal'], unique=False)
    op.create_table('path_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_skill_id', sa.Integer(), nullable=True),
    sa.Column('to_skill_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['to_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_path_transitions_id'), 'path_transitions', ['id'], unique=False)
    op.create_table('user_skill_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_active_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_skill_streaks_id'), 'user_skill_streaks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_skill_streaks_id'), table_name='user_skill_streaks')
    op.drop_table('user_skill_streaks')
    op.drop_index(op.f('ix_path_transitions_id'), table_name='path_transitions')
    op.drop_table('path_transitions')
    op.drop_index(op.f('ix_explanation_cache_target_goal'), table_name='explanation_cache')
    op.drop_index(op.f('ix_explanation_cache_skill_id'), table_name='explanation_cache')
    op.drop_index(op.f('ix_explanation_cache_id'), table_name='explanation_cache')
    op.drop_table('explanation_cache')
    # ### end Alembic commands ###
